--ANALYSIS QUESTIONS
-- RUN AFTER CREATE VIEW OTHERWISE IT WILL SHOW ERROR
--FOR YOU EASE OPEN SHORT SQL QUESRIES FOR DIRECT OPERATION (I MADE THEM BY USING 'VIEW COMMAND'


--Q1 Top 5 car brands in each city by listing count
CREATE VIEW TOP_5_CAR_BRANDS_IN_EACH_CITY AS
SELECT  CAR_BRAND, COUNT(BOOKING_STATUS) AS TOTAL_BOOKINGS
FROM CARS24_DATA
GROUP BY CAR_BRAND;



--Q2 Which brands dominate each fuel type category?
CREATE VIEW DOMINATING_BRANDS AS
SELECT
    FUEL_TYPE,
    CAR_BRAND,
    COUNT(*) AS TOTAL_SALES
FROM CARS24_DATA
WHERE BOOKING_STATUS = 'Purchased'
GROUP BY FUEL_TYPE, CAR_BRAND;


CREATE VIEW DOMINATING_ELECTRIC_BRAND AS
SELECT TOP (1) *
FROM DOMINATING_BRANDS
WHERE FUEL_TYPE = 'Electric'
ORDER BY TOTAL_SALES DESC;


CREATE VIEW DOMINATING_CNG_BRAND AS
SELECT TOP (1) *
FROM DOMINATING_BRANDS
WHERE FUEL_TYPE = 'CNG'
ORDER BY TOTAL_SALES DESC;


CREATE VIEW DOMINATING_PETROL_BRAND AS
SELECT TOP (1) *
FROM DOMINATING_BRANDS
WHERE FUEL_TYPE = 'Petrol'
ORDER BY TOTAL_SALES DESC;


CREATE VIEW DOMINATING_DIESEL_BRAND AS
SELECT TOP (1) *
FROM DOMINATING_BRANDS
WHERE FUEL_TYPE = 'Diesel'
ORDER BY TOTAL_SALES DESC;


SELECT * FROM DOMINATING_ELECTRIC_BRAND;
SELECT * FROM DOMINATING_CNG_BRAND;
SELECT * FROM DOMINATING_PETROL_BRAND;
SELECT * FROM DOMINATING_DIESEL_BRAND;



--Q3 Find the average vehicle age by city
CREATE VIEW AVG_VEHICLE_AGE_BY_CITY AS
SELECT CITY , 
AVG(YEAR (GETDATE())-MANUFACTURING_YEAR) AS AVG_VEHICLE_AGE
FROM CARS24_DATA
GROUP BY CITY;




--Q4 Which car models command the highest average offer price
CREATE VIEW HIGHEST_AVGERAGE_OFFER_PRICE AS
SELECT TOP(10)
    CAR_BRAND,
    CAR_MODEL,
    AVG(CONVERT(BIGINT, OFFER_PRICE)) AS AVG_PRICE
FROM CARS24_DATA
GROUP BY CAR_MODEL, CAR_BRAND
ORDER BY AVG_PRICE DESC;




--Q5 Which brands have the largest average negotiation gap?
CREATE VIEW HIGHEST_NEGOTIATION_GAP AS
SELECT
    CAR_BRAND,
    AVG(CONVERT(BIGINT, OFFER_PRICE)) AS AVG_OFFER_PRICE,
    AVG(CONVERT(BIGINT, EXPECTED_PRICE)) AS AVG_EXPECTED_PRICE,
    AVG(CONVERT(BIGINT, EXPECTED_PRICE))
    -
    AVG(CONVERT(BIGINT, OFFER_PRICE))
    AS NEGOTIATION_GAP
FROM CARS24_DATA
GROUP BY CAR_BRAND;
GO
SELECT * FROM HIGHEST_NEGOTIATION_GAP 
ORDER BY NEGOTIATION_GAP DESC;




--Q6 Find engineers handling the most inspections.
CREATE VIEW TOP_20_INSPECTION_ENGINEERS AS
SELECT TOP(20) INSPECTION_ENGINEER_ID, COUNT(INSPECTION_SCORE) AS INS_SCORE
FROM CARS24_DATA
GROUP BY INSPECTION_ENGINEER_ID
ORDER BY INS_SCORE DESC;




--Q7 Find the highest-performing month by total purchases.
CREATE VIEW MONTHLY_PURCHASES AS
SELECT TOP(1)
DATENAME(MONTH, [Date]) AS Month_Name,
MONTH([Date]) AS Month_No,
COUNT(*) AS Total_Purchases
FROM CARS24_DATA
WHERE Booking_Status = 'Purchased'
GROUP BY DATENAME(MONTH, [Date]), MONTH([Date])
ORDER BY TOTAL_PURCHASES DESC;




--Q8 Which source channels generate the most leads?
CREATE VIEW MOST_LEADS_CHANNEL AS
SELECT SOURCE_CHANNEL , COUNT(LEAD_ID) AS TOTAL_LEADS
FROM CARS24_DATA
GROUP BY SOURCE_CHANNEL
--RUN THIS
SELECT * FROM MOST_LEADS_CHANNEL
ORDER BY TOTAL_LEADS DESC;




--Q9 Which brand generate the most revenue potential?
CREATE VIEW MOST_REVENUE_POTENTIAL_BRAND AS
SELECT TOP(5)
CAR_BRAND,
COUNT(*) AS PURCHASES,
SUM(CONVERT(BIGINT, OFFER_PRICE)) AS TOTAL_VALUE
FROM CARS24_DATA
WHERE BOOKING_STATUS = 'Purchased'
GROUP BY CAR_BRAND
ORDER BY TOTAL_VALUE DESC;




--Q10 Which brand contributes the highest total business value while maintaining strong sales volume?
CREATE VIEW HIGHEST_TOTAL_BV_AND_STRONG_SALES AS
SELECT TOP(5)
CAR_BRAND,
COUNT(*) AS TOTAL_PURCHASES,
SUM(CONVERT(BIGINT, OFFER_PRICE)) AS TOTAL_BUSINESS_VALUE
FROM CARS24_DATA
WHERE BOOKING_STATUS = 'Purchased'
GROUP BY CAR_BRAND
ORDER BY TOTAL_BUSINESS_VALUE DESC,TOTAL_PURCHASES DESC;



